hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,bassa,no,severa,2,3,3,presence).
hh(anziano,female,non_anginoso,normale,alto,normale,2,alta,no,moderata,2,0,7,absence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,0,media,no,lieve,1,0,7,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,0,bassa,si,lieve,2,1,7,absence).
hh(anziano,female,angina_atipica,pre_ipertensione,alto,normale,2,media,si,lieve,1,1,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,normale,normale,0,media,no,lieve,1,0,7,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,alta,2,media,si,lieve,2,1,6,presence).
hh(adulto,male,asintomatico,normale,borderline,normale,2,media,si,moderata,2,1,7,presence).
hh(anziano,male,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,moderata,2,2,7,presence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,severa,2,3,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,borderline,normale,0,alta,no,lieve,2,0,7,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,normale,2,bassa,si,assente,1,0,7,absence).
hh(giovane,male,non_anginoso,ipertensione_lieve,borderline,normale,2,alta,no,assente,1,0,3,absence).
hh(anziano,male,angina_tipica,pre_ipertensione,borderline,normale,0,media,no,severa,2,2,3,presence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,2,alta,no,assente,1,1,3,absence).
hh(anziano,female,asintomatico,normale,normale,normale,0,media,no,moderata,2,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,0,media,si,moderata,2,2,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,alta,2,alta,si,severa,3,0,7,presence).
hh(anziano,male,angina_tipica,normale,borderline,normale,2,media,si,moderata,2,0,3,absence).
hh(giovane,male,angina_tipica,ipertensione_lieve,normale,normale,0,alta,si,moderata,1,0,7,absence).
hh(anziano,male,asintomatico,pre_ipertensione,borderline,normale,2,media,si,severa,2,2,7,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,2,alta,no,lieve,2,0,3,absence).
hh(giovane,male,asintomatico,normale,alto,normale,0,alta,no,moderata,2,0,3,absence).
hh(adulto,male,asintomatico,normale,borderline,normale,0,media,no,lieve,1,0,3,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,alto,alta,2,alta,si,assente,1,1,3,absence).
hh(adulto,female,non_anginoso,pre_ipertensione,alto,normale,0,media,no,lieve,1,0,3,absence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,2,alta,si,assente,2,0,3,absence).
hh(adulto,female,non_anginoso,pre_ipertensione,alto,normale,2,alta,no,lieve,1,0,3,absence).
hh(adulto,male,non_anginoso,normale,borderline,normale,2,alta,no,severa,2,1,7,presence).
hh(anziano,female,non_anginoso,normale,alto,alta,2,media,no,assente,1,1,3,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,borderline,normale,2,alta,no,lieve,2,1,7,presence).
hh(anziano,male,asintomatico,ipertensione_grave,borderline,normale,2,media,no,severa,1,0,6,absence).
hh(giovane,female,non_anginoso,pre_ipertensione,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_grave,alto,normale,2,media,si,severa,3,0,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,normale,2,media,si,lieve,2,0,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,alta,2,alta,si,assente,1,2,7,presence).
hh(anziano,male,asintomatico,ipertensione_lieve,borderline,normale,2,media,si,moderata,1,1,7,presence).
hh(adulto,male,angina_tipica,ipertensione_grave,alto,normale,2,media,no,assente,1,0,3,presence).
hh(giovane,male,non_anginoso,pre_ipertensione,normale,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,borderline,normale,2,alta,no,assente,1,0,3,absence).
hh(giovane,male,asintomatico,ipertensione_lieve,borderline,normale,0,alta,no,assente,1,0,7,presence).
hh(anziano,female,asintomatico,pre_ipertensione,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(giovane,male,non_anginoso,pre_ipertensione,borderline,normale,0,alta,si,lieve,1,0,3,absence).
hh(adulto,male,angina_atipica,normale,normale,alta,0,alta,no,assente,1,0,7,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,borderline,alta,0,media,no,severa,2,1,6,presence).
hh(adulto,male,non_anginoso,ipertensione_lieve,borderline,alta,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,non_anginoso,normale,normale,normale,2,media,no,lieve,1,3,3,presence).
hh(giovane,male,asintomatico,normale,normale,normale,2,alta,no,assente,1,1,3,presence).
hh(anziano,male,angina_atipica,ipertensione_grave,alto,normale,0,media,si,assente,2,3,6,presence).
hh(anziano,female,asintomatico,ipertensione_lieve,borderline,normale,2,bassa,no,lieve,2,3,7,presence).
hh(giovane,male,asintomatico,pre_ipertensione,alto,normale,0,media,si,moderata,2,0,6,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,borderline,alta,0,alta,no,assente,1,0,3,absence).
hh(anziano,female,non_anginoso,ipertensione_lieve,alto,alta,2,alta,no,lieve,1,1,3,absence).
hh(anziano,female,angina_atipica,ipertensione_lieve,normale,normale,0,alta,no,assente,1,2,3,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,borderline,normale,2,alta,no,lieve,2,0,3,absence).
hh(giovane,female,angina_atipica,normale,normale,normale,0,alta,no,assente,1,1,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,normale,normale,2,media,si,severa,2,1,3,presence).
hh(anziano,female,non_anginoso,pre_ipertensione,normale,alta,0,bassa,no,assente,1,0,3,absence).
hh(adulto,female,asintomatico,ipertensione_grave,alto,normale,0,media,si,assente,2,0,3,presence).
hh(anziano,male,angina_atipica,pre_ipertensione,alto,normale,2,bassa,no,moderata,2,1,7,presence).
hh(adulto,male,non_anginoso,ipertensione_lieve,normale,alta,0,alta,no,lieve,1,1,7,absence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,0,media,si,moderata,2,0,7,presence).
hh(giovane,male,non_anginoso,pre_ipertensione,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(anziano,female,angina_tipica,ipertensione_lieve,alto,normale,0,alta,no,lieve,1,0,3,absence).
hh(anziano,male,angina_tipica,ipertensione_lieve,borderline,alta,2,alta,no,severa,3,0,6,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,2,bassa,si,lieve,2,1,6,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,2,alta,si,assente,1,0,3,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,alto,alta,2,alta,no,assente,1,2,3,presence).
hh(giovane,female,non_anginoso,normale,alto,normale,0,media,no,lieve,2,1,3,absence).
hh(adulto,male,non_anginoso,normale,alto,normale,0,alta,no,assente,1,0,3,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,0,media,si,severa,2,1,7,presence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,0,alta,si,lieve,1,0,3,absence).
hh(anziano,male,angina_atipica,ipertensione_lieve,alto,normale,2,media,no,assente,1,0,3,absence).
hh(molto_anziano,female,non_anginoso,ipertensione_lieve,normale,normale,1,bassa,no,moderata,2,0,3,absence).
hh(anziano,female,asintomatico,normale,borderline,normale,0,media,no,lieve,1,2,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,2,media,si,assente,2,3,7,presence).
hh(adulto,male,asintomatico,normale,borderline,normale,2,media,si,severa,2,0,3,absence).
hh(giovane,female,non_anginoso,normale,normale,normale,0,alta,no,assente,1,0,3,absence).
hh(giovane,female,non_anginoso,pre_ipertensione,borderline,normale,0,alta,no,assente,2,0,3,absence).
hh(adulto,male,angina_atipica,pre_ipertensione,borderline,normale,0,alta,no,lieve,1,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,normale,0,bassa,no,moderata,2,1,7,presence).
hh(giovane,male,asintomatico,pre_ipertensione,normale,normale,0,media,si,moderata,2,0,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,2,bassa,si,lieve,1,0,7,presence).
hh(giovane,male,non_anginoso,pre_ipertensione,borderline,normale,2,alta,no,moderata,2,0,3,absence).
hh(adulto,male,asintomatico,normale,borderline,normale,0,media,si,moderata,2,0,6,absence).
hh(giovane,male,angina_tipica,ipertensione_lieve,alto,normale,2,alta,no,lieve,1,2,3,absence).
hh(anziano,male,angina_atipica,pre_ipertensione,borderline,alta,2,media,no,assente,1,0,3,absence).
hh(adulto,male,angina_tipica,ipertensione_grave,alto,normale,2,media,no,severa,3,0,7,absence).
hh(giovane,female,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,2,media,no,severa,2,0,7,presence).
hh(adulto,male,angina_atipica,ipertensione_lieve,borderline,normale,0,alta,si,assente,1,0,3,absence).
hh(anziano,female,asintomatico,pre_ipertensione,alto,normale,2,alta,no,assente,1,0,3,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,bassa,si,severa,2,1,7,presence).
hh(adulto,male,asintomatico,normale,borderline,normale,2,bassa,si,assente,2,1,3,presence).
hh(adulto,male,asintomatico,pre_ipertensione,borderline,normale,0,alta,no,lieve,1,2,7,presence).
hh(adulto,male,asintomatico,normale,alto,normale,2,bassa,si,lieve,2,1,3,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,alta,no,lieve,2,0,3,absence).
hh(adulto,male,asintomatico,normale,borderline,normale,0,alta,no,lieve,1,1,7,presence).
hh(anziano,female,non_anginoso,ipertensione_lieve,alto,normale,0,media,no,lieve,1,0,7,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,moderata,1,0,3,absence).
hh(giovane,female,non_anginoso,normale,normale,normale,0,alta,no,lieve,2,0,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,borderline,normale,0,bassa,no,lieve,2,0,3,presence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_grave,alto,alta,2,media,no,lieve,2,3,7,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,media,no,moderata,2,1,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,alta,no,lieve,2,0,7,presence).
hh(adulto,male,non_anginoso,normale,borderline,normale,0,media,si,moderata,2,0,3,absence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,severa,2,2,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,normale,normale,0,alta,si,assente,1,1,7,presence).
hh(adulto,female,angina_atipica,normale,normale,normale,0,media,no,assente,2,0,3,absence).
hh(adulto,female,asintomatico,ipertensione_grave,alto,normale,1,bassa,si,severa,2,0,3,presence).
hh(giovane,male,angina_atipica,normale,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,assente,1,0,3,presence).
hh(adulto,female,non_anginoso,pre_ipertensione,alto,alta,0,alta,no,assente,1,0,3,absence).
hh(giovane,male,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,assente,2,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,media,no,lieve,1,0,7,presence).
hh(adulto,female,asintomatico,ipertensione_grave,alto,alta,2,media,si,severa,3,2,7,presence).
hh(anziano,female,angina_tipica,ipertensione_lieve,borderline,normale,0,bassa,no,severa,3,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,alta,2,bassa,si,moderata,3,0,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,normale,normale,0,media,no,moderata,2,3,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,bassa,si,severa,2,2,3,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,0,bassa,si,moderata,2,1,7,presence).
hh(anziano,female,non_anginoso,ipertensione_grave,alto,normale,2,alta,no,lieve,1,0,3,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,normale,2,alta,no,lieve,3,1,3,absence).
hh(adulto,female,non_anginoso,ipertensione_grave,borderline,normale,0,alta,no,assente,1,1,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,0,bassa,si,moderata,2,2,7,presence).
hh(adulto,female,non_anginoso,pre_ipertensione,normale,normale,2,alta,no,lieve,2,0,3,absence).
hh(adulto,male,angina_atipica,pre_ipertensione,borderline,normale,0,alta,no,lieve,1,1,3,absence).
hh(anziano,male,asintomatico,normale,borderline,alta,0,alta,si,moderata,1,2,7,presence).
hh(anziano,female,asintomatico,normale,alto,normale,0,alta,si,moderata,2,2,3,presence).
hh(anziano,male,asintomatico,normale,borderline,normale,2,media,si,lieve,1,1,3,presence).
hh(giovane,male,asintomatico,ipertensione_lieve,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,bassa,si,severa,3,1,3,presence).
hh(adulto,male,non_anginoso,ipertensione_lieve,borderline,normale,2,alta,no,moderata,1,0,7,absence).
hh(adulto,female,non_anginoso,ipertensione_lieve,normale,normale,2,alta,si,moderata,3,0,3,absence).
hh(anziano,female,non_anginoso,ipertensione_lieve,alto,normale,0,alta,no,assente,1,1,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,alta,2,media,si,moderata,2,1,3,presence).
hh(giovane,female,angina_atipica,normale,borderline,normale,0,alta,no,lieve,1,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,borderline,normale,0,alta,si,assente,1,0,7,absence).
hh(anziano,male,asintomatico,ipertensione_lieve,borderline,normale,2,media,no,moderata,2,2,6,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,non_anginoso,ipertensione_lieve,borderline,normale,0,alta,no,lieve,2,1,7,presence).
hh(adulto,male,angina_tipica,pre_ipertensione,borderline,normale,2,media,si,moderata,1,1,3,absence).
hh(adulto,male,angina_atipica,ipertensione_grave,alto,normale,2,alta,no,assente,1,1,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,0,bassa,si,moderata,2,2,7,presence).
hh(adulto,male,asintomatico,normale,borderline,normale,0,alta,no,assente,1,1,3,presence).
hh(giovane,male,asintomatico,normale,normale,normale,2,bassa,si,moderata,2,0,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,borderline,normale,2,alta,no,severa,1,2,7,presence).
hh(giovane,female,non_anginoso,normale,alto,normale,2,alta,si,assente,1,0,3,absence).
hh(giovane,male,non_anginoso,normale,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,female,non_anginoso,pre_ipertensione,borderline,normale,0,alta,no,moderata,2,0,3,absence).
hh(adulto,female,non_anginoso,normale,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(anziano,female,asintomatico,pre_ipertensione,alto,normale,0,media,no,moderata,2,2,3,absence).
hh(adulto,female,non_anginoso,pre_ipertensione,alto,normale,2,media,no,lieve,1,0,3,absence).
hh(adulto,female,angina_atipica,normale,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,normale,0,bassa,si,severa,3,0,7,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,angina_tipica,pre_ipertensione,normale,normale,2,alta,no,moderata,2,0,7,absence).
hh(anziano,female,asintomatico,ipertensione_grave,borderline,alta,0,alta,si,lieve,2,2,7,presence).
hh(giovane,male,angina_tipica,pre_ipertensione,borderline,normale,0,alta,si,severa,2,0,7,presence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,0,alta,si,moderata,2,0,3,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,media,si,severa,2,2,7,presence).
hh(giovane,male,asintomatico,normale,borderline,normale,0,alta,no,assente,1,0,7,absence).
hh(anziano,female,asintomatico,ipertensione_grave,alto,normale,0,alta,si,assente,1,0,3,absence).
hh(adulto,female,asintomatico,normale,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,normale,alta,2,alta,no,moderata,3,0,3,absence).
hh(adulto,female,asintomatico,pre_ipertensione,borderline,normale,2,alta,si,lieve,2,0,3,absence).
hh(anziano,male,angina_tipica,pre_ipertensione,alto,alta,2,alta,no,moderata,2,1,3,presence).
hh(anziano,male,angina_tipica,ipertensione_grave,borderline,alta,2,media,no,lieve,2,1,3,absence).
hh(anziano,male,non_anginoso,ipertensione_lieve,alto,normale,2,media,no,moderata,2,3,7,presence).
hh(anziano,male,asintomatico,normale,alto,normale,2,media,si,lieve,2,2,3,presence).
hh(anziano,female,non_anginoso,pre_ipertensione,borderline,normale,2,bassa,no,moderata,2,0,3,absence).
hh(giovane,male,angina_tipica,normale,normale,normale,2,alta,no,assente,1,0,3,absence).
hh(anziano,female,asintomatico,pre_ipertensione,alto,alta,0,bassa,no,moderata,2,3,3,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,0,media,si,severa,2,3,7,presence).
hh(adulto,male,non_anginoso,ipertensione_lieve,borderline,normale,0,media,no,severa,2,0,3,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,alta,0,alta,no,lieve,2,2,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,normale,normale,0,alta,no,assente,1,0,3,absence).
hh(giovane,male,non_anginoso,pre_ipertensione,alto,alta,0,alta,no,lieve,3,0,7,absence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,2,alta,si,moderata,2,2,7,presence).
hh(giovane,male,asintomatico,normale,normale,normale,2,alta,no,assente,1,0,7,presence).
hh(giovane,female,asintomatico,normale,alto,normale,2,media,no,lieve,2,0,3,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,alta,2,alta,no,assente,1,3,3,absence).
hh(giovane,male,non_anginoso,pre_ipertensione,alto,normale,0,alta,no,moderata,1,1,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,normale,normale,2,bassa,si,severa,2,1,6,presence).
hh(adulto,male,asintomatico,normale,borderline,alta,0,media,no,lieve,1,3,7,absence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,moderata,2,0,3,absence).
hh(anziano,male,non_anginoso,ipertensione_grave,alto,normale,0,bassa,si,severa,2,1,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,borderline,normale,0,alta,no,moderata,1,0,3,absence).
hh(anziano,male,asintomatico,ipertensione_lieve,normale,normale,0,media,si,severa,3,0,7,presence).
hh(adulto,male,angina_atipica,normale,alto,normale,0,alta,no,assente,1,0,7,absence).
hh(giovane,male,asintomatico,pre_ipertensione,alto,normale,2,alta,si,assente,1,0,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,alta,0,alta,no,assente,1,2,3,absence).
hh(adulto,female,angina_atipica,pre_ipertensione,alto,normale,2,alta,no,moderata,2,0,3,absence).
hh(adulto,female,asintomatico,normale,alto,normale,2,media,no,lieve,2,0,3,absence).
hh(adulto,female,non_anginoso,normale,borderline,normale,0,alta,no,moderata,2,0,3,absence).
hh(anziano,female,angina_tipica,ipertensione_lieve,borderline,normale,0,alta,no,moderata,1,2,3,absence).
hh(molto_anziano,male,asintomatico,pre_ipertensione,alto,normale,2,alta,si,assente,1,3,3,presence).
hh(anziano,male,non_anginoso,normale,alto,normale,0,alta,no,lieve,1,1,7,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,2,alta,no,assente,1,2,7,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,media,si,severa,2,1,7,presence).
hh(adulto,male,asintomatico,ipertensione_lieve,alto,normale,0,alta,si,moderata,1,0,7,presence).
hh(adulto,male,asintomatico,ipertensione_grave,alto,normale,2,media,si,lieve,2,1,7,presence).
hh(adulto,male,angina_tipica,ipertensione_lieve,alto,alta,0,alta,no,moderata,2,0,7,absence).
hh(anziano,female,non_anginoso,normale,alto,normale,0,alta,no,assente,1,1,3,absence).
hh(adulto,male,non_anginoso,normale,alto,normale,2,alta,si,lieve,2,0,7,absence).
hh(anziano,male,non_anginoso,pre_ipertensione,alto,normale,0,media,si,moderata,2,0,7,presence).
hh(giovane,male,non_anginoso,pre_ipertensione,alto,normale,0,alta,no,severa,3,0,3,absence).
hh(adulto,male,angina_tipica,ipertensione_grave,alto,normale,2,alta,no,lieve,2,0,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,alta,2,alta,no,severa,2,0,3,absence).
hh(giovane,female,non_anginoso,pre_ipertensione,borderline,normale,0,alta,no,lieve,2,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,borderline,normale,2,media,si,severa,2,3,7,presence).
hh(giovane,male,angina_atipica,pre_ipertensione,borderline,normale,2,alta,no,assente,1,0,3,absence).
hh(giovane,female,angina_atipica,pre_ipertensione,borderline,normale,2,alta,no,moderata,1,0,3,absence).
hh(anziano,female,non_anginoso,pre_ipertensione,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,non_anginoso,normale,borderline,normale,0,alta,si,assente,1,1,7,absence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,normale,2,media,no,lieve,2,0,7,absence).
hh(giovane,male,angina_atipica,pre_ipertensione,borderline,normale,0,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,normale,borderline,normale,0,media,si,severa,2,1,7,presence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,2,media,no,severa,2,1,7,presence).
hh(adulto,male,non_anginoso,ipertensione_lieve,normale,normale,0,alta,no,moderata,1,0,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,alta,2,media,si,moderata,1,3,7,presence).
hh(giovane,female,asintomatico,pre_ipertensione,normale,normale,0,alta,no,moderata,1,0,3,absence).
hh(giovane,male,angina_atipica,pre_ipertensione,borderline,normale,0,media,no,assente,2,0,6,absence).
hh(anziano,female,non_anginoso,pre_ipertensione,alto,normale,0,bassa,no,moderata,2,1,7,presence).
hh(giovane,female,asintomatico,pre_ipertensione,alto,alta,2,media,si,severa,2,0,7,presence).
hh(adulto,female,angina_tipica,ipertensione_lieve,alto,alta,2,alta,no,lieve,1,0,3,absence).
hh(adulto,male,angina_tipica,normale,normale,normale,2,alta,no,assente,2,0,6,absence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,media,si,lieve,2,0,7,presence).
hh(giovane,male,asintomatico,normale,borderline,normale,0,media,no,moderata,2,0,7,presence).
hh(adulto,male,asintomatico,normale,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,0,alta,si,assente,1,1,7,presence).
hh(anziano,male,non_anginoso,pre_ipertensione,borderline,normale,0,media,no,moderata,2,3,7,absence).
hh(anziano,female,asintomatico,ipertensione_grave,normale,normale,2,media,no,severa,3,3,7,presence).
hh(adulto,female,asintomatico,pre_ipertensione,borderline,normale,2,alta,no,assente,1,0,3,absence).
hh(giovane,male,asintomatico,pre_ipertensione,normale,normale,2,media,si,severa,2,0,7,presence).
hh(adulto,male,non_anginoso,pre_ipertensione,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,lieve,1,0,3,absence).
hh(anziano,male,non_anginoso,ipertensione_grave,alto,alta,2,alta,si,moderata,2,0,7,presence).
hh(giovane,male,non_anginoso,ipertensione_lieve,alto,normale,2,alta,no,assente,1,0,3,absence).
hh(adulto,female,asintomatico,pre_ipertensione,alto,normale,2,media,no,lieve,2,0,3,absence).
hh(anziano,female,asintomatico,ipertensione_lieve,alto,normale,2,alta,no,severa,3,2,3,presence).
hh(adulto,female,non_anginoso,ipertensione_lieve,alto,normale,2,media,no,moderata,1,1,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,alto,normale,0,media,si,moderata,1,1,7,presence).
hh(anziano,male,asintomatico,normale,alto,normale,2,alta,no,lieve,1,2,6,presence).
hh(anziano,female,non_anginoso,ipertensione_lieve,alto,normale,0,media,no,lieve,1,0,3,absence).
hh(anziano,male,non_anginoso,ipertensione_lieve,normale,normale,2,alta,no,severa,2,0,3,presence).
hh(anziano,male,asintomatico,ipertensione_lieve,alto,normale,2,media,si,severa,2,2,7,presence).
hh(adulto,male,asintomatico,pre_ipertensione,normale,normale,0,bassa,no,moderata,2,1,7,presence).
hh(giovane,male,angina_atipica,pre_ipertensione,borderline,normale,2,alta,no,assente,1,0,3,absence).
hh(giovane,male,asintomatico,normale,alto,normale,2,alta,no,assente,1,1,3,presence).
hh(adulto,male,non_anginoso,normale,normale,normale,0,media,no,lieve,1,0,3,absence).
hh(adulto,male,non_anginoso,ipertensione_lieve,borderline,alta,0,alta,no,moderata,1,0,3,absence).
hh(anziano,female,angina_atipica,ipertensione_grave,alto,normale,0,alta,no,lieve,1,2,3,absence).
hh(anziano,male,non_anginoso,ipertensione_lieve,alto,alta,0,media,si,lieve,2,0,3,absence).
hh(adulto,male,asintomatico,pre_ipertensione,alto,normale,0,media,si,moderata,2,1,7,presence).
hh(anziano,male,non_anginoso,ipertensione_lieve,alto,normale,0,alta,no,assente,1,0,3,presence).
hh(giovane,male,asintomatico,ipertensione_lieve,alto,normale,0,alta,no,moderata,1,0,3,absence).
hh(adulto,female,non_anginoso,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,3,absence).
hh(anziano,male,asintomatico,pre_ipertensione,borderline,normale,2,media,si,severa,2,2,7,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,2,alta,no,moderata,2,0,3,presence).
hh(adulto,male,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,lieve,1,0,3,absence).
hh(adulto,male,angina_atipica,normale,borderline,normale,0,alta,no,lieve,3,0,7,presence).
hh(adulto,male,non_anginoso,ipertensione_grave,normale,alta,0,alta,no,lieve,1,0,7,absence).
hh(giovane,male,angina_atipica,pre_ipertensione,alto,normale,0,alta,no,assente,1,0,7,absence).
hh(adulto,female,angina_atipica,ipertensione_lieve,alto,normale,2,alta,no,moderata,2,0,3,absence).
hh(adulto,male,asintomatico,ipertensione_lieve,normale,normale,0,media,no,lieve,2,0,6,absence).
hh(anziano,male,asintomatico,ipertensione_grave,alto,normale,2,bassa,si,moderata,2,3,3,presence).
